joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
BaseLink_Leg1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link_leg1_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}